name: Deploy to GitHub Pages

on:
  push:
    branches:
      - live

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir -p _site
          cp -pv index.html _site/
          cp -rpv build/ _site/build/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3

      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: github-pages
      #     path: ${{ runner.temp }}/artifact.tar
      #     retention-days: 1
      #     if-no-files-found: error

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v4
